#Code by Madhavan Parthiban
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: team3
    region: ap-southeast-1
managedNodeGroups:
    - name: Team3
      instanceType: t2.large
      desiredCapacity: 2
      minSize: 2
      maxSize: 5
      ssh:
          publicKeyName: Team3
